version: "2"
run:
  build-tags:
    - lint
  tests: true
output:
  formats:
    text:
      path: stdout
      print-issued-lines: false
      colors: false
linters:
  default: none
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          deny:
            - pkg: errors
            - pkg: github.com/pkg/errors
            - pkg: flag
            - pkg: log
            - pkg: github.com/go-kit/kit/log
            - pkg: github.com/go-kit/kit/log/level
            - pkg: github.com/go-kit/log
            - pkg: github.com/go-kit/log/level
            - pkg: encoding/json
            - pkg: unsafe
          allow:
            - $gostd
            - go.opentelemetry.io/otel 
            - go.opentelemetry.io/contrib
            - github.com/stretchr/testify/assert
            - github.com/hashicorp/go-retryablehttp
            - github.com/segmentio/encoding/json
            - google.golang.org/protobuf
            - golang.org/x
            - github.com/rs/xid
            - github.com/gsmcwhirter/go-util/v12
            - github.com/spf13/cobra

    gocritic:
      disabled-checks:
        - commentedOutCode
        - equalFold
        - exitAfterDefer
        - hugeParam
        - ifElseChain
        - octalLiteral
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - deepequalerrors
      settings:
        shadow:
          strict: true
    nakedret:
      max-func-lines: 6
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/gsmcwhirter/go-util
    gofumpt:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
